### ISSUE TITLE
Add "lv2:appliesTo" to bank definitions in presets

### ISSUE THREAD

**Issue by jofemodo** [jpcima/miniopl3#1]
Adding this:

`lv2:appliesTo <http://jpcima.sdf1.org/lv2/miniopl3> ;`

to bank definitions in presets would be nice (and it would ease zynthian integration ;-)

**Comment by jpcima** [comment]
Hi, the generator was fixed in 9780ca8.

**Comment by jpcima** [comment]
Also, I wrote a README for a rapid explanation of the presets.

**Comment by jofemodo** [comment]
Thank a lot!

But ... it should be "pset:bank" instead of "pset:Bank"... ;-)

**Comment by jpcima** [comment]
>But ... it should be "pset:bank" instead of "pset:Bank"... ;-)

Where? no it shouldn't, unless I'm mistaken.
There exists "pset:Bank", the class, and "pset:bank", the attribute.

**Comment by jofemodo** [comment]
OK! Sorry. My mistake ...
